# Generated by Django 4.1.1 on 2022-11-23 11:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApolloClient',
            fields=[
                ('app_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='AppId')),
                ('env', models.CharField(max_length=10, verbose_name='Env')),
                ('app_name', models.CharField(blank=True, max_length=50, verbose_name='AppName')),
                ('department', models.CharField(max_length=30, verbose_name='Department')),
                ('principal', models.CharField(max_length=30, verbose_name='Principal')),
                ('username', models.CharField(max_length=15, verbose_name='Username')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'apollo_client',
                'ordering': ['-update_date'],
            },
        ),
        migrations.CreateModel(
            name='ApolloAppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(default='default', max_length=20, verbose_name='ClusterName')),
                ('namespace_name', models.CharField(max_length=20, verbose_name='NamespaceName')),
                ('item_key', models.CharField(max_length=30, verbose_name='ItemKey')),
                ('item_value', models.TextField(max_length=1000, verbose_name='ItemValue')),
                ('item_comment', models.TextField(max_length=200, verbose_name='ItemComment')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('belong_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apollo.apolloclient')),
            ],
            options={
                'db_table': 'apollo_app_info',
                'ordering': ['-update_date'],
            },
        ),
    ]
