# Generated by Django 4.1.3 on 2023-01-13 17:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apollo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApolloApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(default='default', max_length=20, verbose_name='ClusterName')),
                ('namespace_name', models.CharField(default='application', max_length=20, verbose_name='NamespaceName')),
                ('item_key', models.CharField(max_length=30, verbose_name='ItemKey')),
                ('item_value', models.TextField(max_length=1000, verbose_name='ItemValue')),
                ('item_comment', models.TextField(blank=True, max_length=200, verbose_name='ItemComment')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'apollo_app',
                'ordering': ['-update_date'],
            },
        ),
        migrations.CreateModel(
            name='ApolloInstance',
            fields=[
                ('app_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='AppId')),
                ('env', models.CharField(max_length=20, verbose_name='Env')),
                ('app_name', models.CharField(blank=True, max_length=50, verbose_name='AppName')),
                ('department', models.CharField(max_length=30, verbose_name='Department')),
                ('principal', models.CharField(max_length=30, verbose_name='Principal')),
                ('username', models.CharField(max_length=15, verbose_name='Username')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'apollo_instance',
                'ordering': ['-update_date'],
            },
        ),
        migrations.DeleteModel(
            name='ApolloAppInfo',
        ),
        migrations.DeleteModel(
            name='ApolloClient',
        ),
        migrations.AddField(
            model_name='apolloapp',
            name='belong_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app', to='apollo.apolloinstance'),
        ),
    ]
