# Generated by Django 4.1.3 on 2023-02-21 08:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CICDFlow',
            fields=[
                ('email_title', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='邮件标题')),
                ('sql_info', models.JSONField(verbose_name='SVN 信息')),
                ('config_info', models.JSONField(verbose_name='配置文件信息')),
                ('apollo_info', models.JSONField(verbose_name='Apollo 信息')),
                ('project_info', models.JSONField(verbose_name='工程信息')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'upgrade_flow',
                'ordering': ['-update_date'],
            },
        ),
        migrations.CreateModel(
            name='JiraWorkflow',
            fields=[
                ('issue_key', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='编号key值')),
                ('issue_id', models.CharField(max_length=32, verbose_name='编号ID')),
                ('summary', models.CharField(max_length=255, unique=True, verbose_name='概要标题')),
                ('status', models.CharField(max_length=64, verbose_name='当前状态')),
                ('project', models.CharField(max_length=16, verbose_name='归属项目')),
                ('priority', models.CharField(max_length=16, verbose_name='优先级')),
                ('labels', models.JSONField(blank=True, null=True, verbose_name='标签')),
                ('environment', models.CharField(max_length=16, verbose_name='升级环境')),
                ('sql_info', models.JSONField(default=list, verbose_name='SQL升级信息')),
                ('apollo_info', models.JSONField(default=list, verbose_name='Apollo升级信息')),
                ('config_info', models.JSONField(default=list, verbose_name='配置升级信息')),
                ('code_info', models.JSONField(default=list, verbose_name='代码升级信息')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jira_workflow',
                'ordering': ['-update_date'],
            },
        ),
        migrations.CreateModel(
            name='CICDState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_state', models.IntegerField(choices=[(0, '执行成功/无需执行'), (1, '执行失败'), (2, '执行中，未返回状态'), (3, '待执行.'), (9, '未知状态')], default=9, verbose_name='SQL 升级执行状态')),
                ('config_state', models.IntegerField(choices=[(0, '执行成功/无需执行'), (1, '执行失败'), (2, '执行中，未返回状态'), (3, '待执行.'), (9, '未知状态')], default=9, verbose_name='配置文件升级执行状态')),
                ('apollo_state', models.IntegerField(choices=[(0, '执行成功/无需执行'), (1, '执行失败'), (2, '执行中，未返回状态'), (3, '待执行.'), (9, '未知状态')], default=9, verbose_name='Apollo 升级执行状态')),
                ('project_state', models.IntegerField(choices=[(0, '执行成功/无需执行'), (1, '执行失败'), (2, '执行中，未返回状态'), (3, '待执行.'), (9, '未知状态')], default=9, verbose_name='代码升级执行状态')),
                ('flow_state', models.IntegerField(choices=[(0, '执行成功/无需执行'), (1, '执行失败'), (2, '执行中，未返回状态'), (3, '待执行.'), (9, '未知状态')], default=3, verbose_name='工作流状态')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('email_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cicdstate', to='cicdflow.cicdflow')),
            ],
            options={
                'db_table': 'cicd_state',
                'ordering': ['-update_date'],
            },
        ),
    ]
