# Generated by Django 4.1.3 on 2024-04-18 06:34

import cicdflow.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('issue_key', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='编号key值')),
                ('issue_id', models.CharField(max_length=32, verbose_name='编号ID')),
                ('jira_project', models.CharField(default='UPGRADE', max_length=16, verbose_name='Jira项目名称')),
                ('issue_type', models.CharField(default='升级', max_length=16, verbose_name='事件类型')),
                ('product_id', models.CharField(max_length=32, verbose_name='归属产品')),
                ('summary', models.CharField(max_length=255, unique=True, verbose_name='概要标题')),
                ('issue_status', models.CharField(max_length=64, verbose_name='事件当前状态')),
                ('environment', models.CharField(max_length=16, verbose_name='升级环境')),
                ('close_hall', models.CharField(max_length=8, verbose_name='升级是否需要维护')),
                ('function_list', models.TextField(verbose_name='功能列表')),
                ('sql_info', models.JSONField(null=True, verbose_name='SQL升级信息')),
                ('nacos_info', models.JSONField(null=True, verbose_name='Nacos升级信息')),
                ('config_info', models.JSONField(null=True, verbose_name='配置升级信息')),
                ('code_info', models.JSONField(null=True, verbose_name='代码升级信息')),
                ('init_flag', models.JSONField(default=cicdflow.models.init_data, verbose_name='初始化升级标志')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jira_issue',
                'ordering': ['-update_date'],
            },
        ),
        migrations.CreateModel(
            name='SqlWorkflow',
            fields=[
                ('w_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Archery工单ID')),
                ('sql_index', models.IntegerField(default=0, verbose_name='SQL文件升级序号')),
                ('sql_filename', models.CharField(max_length=255, verbose_name='SQL文件名称')),
                ('sql_release_info', models.CharField(default=0, max_length=64, verbose_name='SQL文件版本信息')),
                ('workflow_name', models.CharField(max_length=255, verbose_name='工单名称')),
                ('w_status', models.CharField(max_length=64, verbose_name='工单状态')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sql_workflow',
                'ordering': ['workflow_name', 'sql_index'],
            },
        ),
    ]
