# Generated by Django 4.1.3 on 2024-04-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicdflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraissue',
            name='code_info',
            field=models.JSONField(null=True, verbose_name='代码升级信息'),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='config_info',
            field=models.JSONField(null=True, verbose_name='配置升级信息'),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='nacos_info',
            field=models.JSONField(null=True, verbose_name='Nacos升级信息'),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='sql_info',
            field=models.JSONField(null=True, verbose_name='SQL升级信息'),
        ),
    ]
