# Generated by Django 4.1.3 on 2024-04-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicdflow', '0002_alter_jiraissue_code_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraissue',
            name='function_list',
            field=models.TextField(verbose_name='功能列表'),
        ),
    ]
